---


- hosts: 192.168.100.178
  become: true
  tasks:
  
  - name: Instalacion de vim
    apt:
      name: vim
      state: present

  - name: Agregar Repositorio de Maven 
    shell: apt-add-repository ppa:andrei-pozolotin/maven3

  - name: Agregar Repositorio de Java 8
    shell: add-apt-repository ppa:webupd8team/java -y

  - name: Crea el directorio /root/MPTCP 
    file: path=/root/MPTCP state=directory owner=root group=root

  - name: copiar archivo que contiene el codigo desarrollado y descomprimirlo 
    unarchive:
      src=/home/odl/Desktop/bottleneck-Mptcp2.tar.gz 
      dest=/root/MPTCP/ 

  - name: Agregar las llaves del servidor que se encuentra los repositorios de MPTCP keyserver
    apt_key:
      keyserver: keys.gnupg.net
      id: 379CE192D401AB61
      state: present
  - name: Agregar las llaves del servidor que se encuentra los repositorios de MPTCP keyserver
    shell: apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 379CE192D401AB61

  - name: Instalar el repositorio de MPTCP
    shell: if [ `cat /etc/apt/sources.list | grep -c "dl.bintray.com/cpaasch/deb"` == 1 ]; then echo "ya se encuentra"; else echo "deb https://dl.bintray.com/cpaasch/deb jessie main" >> /etc/apt/sources.list ; fi

  - name: Instalacion csh
    apt:
      name: csh
      state: present

  - name: Instalar el repositorio de MPTCP
    shell: if [ `cat /etc/apt/sources.list | grep -c "dl.bintray.com/cpaasch/deb"` == 1 ]; then echo "ya se encuentra"; else echo "deb https://dl.bintray.com/cpaasch/deb jessie main" >> cat /etc/apt/sources.list ; fi


  - name: Actualizar a apt packages
    become: true
    apt:
      update_cache: yes

  - name: Instalacion Jdk 7
    apt:
      name: openjdk-7-jdk
      state: present
  - name: Intalacion de Mininet
    apt:
      name: git
      state: present
  - name: Intalacion de Mininet	  
    shell: git clone git://github.com/mininet/mininet; mininet/util/install.sh -a

  - name: Instalacion del paquete MPTCP
    apt:
      name: linux-mptcp
      state: present

  - name: Instalacion Maven3
    apt:
      name: maven3
      state: present

  - name: Agregar archivo settings .m2
    shell: mkdir /root/.m2

  - name: Agregar settings.xml a .m2
    shell: echo "a" > /root/.m2/settings.xml

  - name: reparar archivo .m2 settings.xml
    shell: cp -n /root/.m2/settings.xml{,.orig} ; wget -q -O - https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml > ~/.m2/settings.xml

  - name: ejecutar maven clean install en la carpeta bottleneck-Mptcp 
    shell: mvn clean install
    args:
      chdir: /root/MPTCP/bottleneck-Mptcp/

  - name: Reiniciar el Host Cliente 
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
